name: Welcome New Contributor

on:
  issues:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Send a welcome message
        env:
          GITHUB_TOKEN: ${{ github.token }}
      with:
        message: Добро пожаловать! Спасибо, что присоединились к нашему проекту!


          
