name: Welcome New Contributor

on:
  issues:
    types: [opened]

jobs:
  add_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add comment to issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Привет! Спасибо за создание issue.'
            })

